### ISSUE TITLE
Roadmap to completeness

### ISSUE THREAD

**Issue by alula** [doukutsu-rs/doukutsu-rs#10]
#### Gameplay support roadmap

- Checkmarked things = fully implemented
- Unmarked things = partially or not implemented yet.

- [x] Misc stuff tbd
  - [x] Whimsical star
  - [x] Map System
- [x] Text scripts (TSC)
  - [x] Initial implementation
  - [x] Full implementation of gameplay opcodes
  - [x] Shift-JIS encoding support
  - [x] Credits opcodes
  - [x] Nikumaru/290 counter
- [x] Audio
  - [x] Organya BGM playback
  - [x] Text script bindings
  - [x] CS+ style .ogg BGM playback
  - [x] PixTone SFX
- [x] NPCs/entities
  - [x] Initial implementation
  - [x] Miscellaneous entities
  - [x] Major Bosses
    - [x] Omega
    - [x] Balfrog
    - [x] Monster X
    - [x] Core
    - [x] Ironhead
    - [x] Twins
    - [x] Undead Core
    - [x] Press
    - [x] Ballos
  - [x] First Cave
  - [x] Mimiga Village
  - [x] Egg Corridor
  - [x] Grasstown
  - [x] Sand Zone
  - [x] Labirynth I
  - [x] Labirynth H
  - [x] Labirynth W
  - [x] Labirynth B
  - [x] Labirynth M
  - [x] Core Room
  - [x] Waterway
  - [x] Egg Corridor?
  - [x] Outer Wall
  - [x] Plantation
  - [x] Last Cave
  - [x] Balcony
  - [x] Ma Pignon Quest
  - [x] Hell
- [x] Weapons
  - [x] Leveling / XP system
  - [x] Initial implementation
  - [x] Snake
  - [x] Polar Star
  - [x] Fireball
  - [x] Machine Gun
  - [x] Missile Launcher
  - [x] Bubbler
  - [x] Blade
  - [x] Super Missile Launcher
  - [x] Nemesis
  - [x] Spur
- [x] Saving and loading game state
- [ ] Support for different game editions
  - [ ] Freeware
  - [x] Modified freeware
  - [x] Cave Story+ (PC/Switch)
    - [x] Base mod
    - [ ] Mod loading
    - [x] Seasonal graphics
    - [x] Co-op gameplay

**Comment by alula** [comment]
we're done ig
